# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0130ca7193ac62a3103920b7706513d11f6091502e9be384e263b2ccac4a56cf6f7d5b429e72c3dbc623128ba8a68ba1c99cded3a2c7b74e78f0569b40b334e7

test:
  secret_key_base: cfb134e1e75b07b8071b8b6eaf40806e400f7dfa67ca8640982870b43fae4c8371fe3431b24f103ffb703e4fe69ed912b3bcac967c71082d695bce6ed4089bc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
